# Generated by Django 4.0.6 on 2022-08-17 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_ticket_last_edited_alter_ticket_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
